### PR TITLE
Upgraded from uber-raven to raven@2.3.0

### PR DESCRIPTION
**Pull request by ajbogh**
uber-raven should be deprecated since it doesn't track the latest version of raven.

### CODE REVIEW

**Comment by ajbogh** [comment]
Please note that this change also cleans up the following console warnings: 

```
    console.warn node_modules/uber-raven/node_modules/node-uuid/uuid.js:48
      [SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()
```

**Comment by rimiti** [comment]
Up ?

**Comment by ajbogh** [comment]
Not sure I understand what you're asking.

**Comment by AlexMSmithCA** [comment]
+1 from Web Platform Team.  Warning is being surfaced for new [Fusion.js](https://github.com/fusionjs/fusion-core) apps.

**Comment by ajbogh** [comment]
Can someone please mergr this or let me know if there's anything else you'd like me to do? It's been open for 8 months and we have new issues in the open source fusion code. Please merge and close if this works.

**Comment by lhorie** [comment]
I don't have much context here and this PR generally looks ok for me and it appears I do have access to merge, so there.

**Comment by ajbogh** [comment]
@lhorie Can you also publish the update?

**Pull request merged**
